### ISSUE TITLE
SPI byte transfers happen too fast in a single transaction

### ISSUE THREAD

**Issue by tabarr** [ARMmbed/example-asynch-spi#17] opened 2015-11-03 17:19 UTC
Taking the async SPI transfer example as a starting point, I modified the code to try to communicate with a SPI slave device (Atmel AT86RF233),by  trying to read the ID register. This simple action was not successful. Looking at the waveforms, I found that consecutive bytes in a single transfer in the spi transaction were happening too fast for the slave part to process data. Going back to the original codebase, I then looked at clock timing and found that the time between bytes in a transaction was only 104 nsecs. With a default clock of 1 MHz, this is not even 1/2 a clock period (500 nS). The slave device I was trying to test required a minimum of 250 nsec between SPI frames. There needs to be some way to set this or at least default the delay between bytes in a transaction to 1/2 clock cycle.

**Comment by 0xc0170** [comment] 2015-11-03 18:14
@tabarr just checking , using k64f ?

**Comment by 0xc0170** [comment] 2015-11-04 09:04
This might be better to ask in ksdk module, but lets just pinpoint the root cause here.

I looked at DSPI reference manual there is CTAR register configuring delays. There's a function SetDelay in KSDK, which is invoked in spi init, file reference https://github.com/ARMmbed/mbed-hal-ksdk-mcu/blob/master/source/spi_api.c#L75. The function provides a way to configure 3 delay types. The init configures the SPI to the default state, I believe same as KSDK drivers, if you spot the wrong settings, let us know. Or just send a pull request to the ksdk module.

For further details how ksdk set delay is implemented and what it provides: https://github.com/ARMmbed/mbed-hal-ksdk-mcu/blob/master/source/TARGET_KSDK_CODE/hal/dspi/fsl_dspi_hal.c#L309 and check dspi hal header file.

**Comment by tabarr** [comment] 2015-11-04 15:04
I am using a K64F like target. Looking at the source code link, the default state for delay looks to be set to minimum, which is definitely too short for the Atmel slave device.I think this delay needs to be adjustable at the mbed SPI object level, or automatically set to 1/2 the clock rate, if possible.

**Comment by 0xc0170** [comment] 2015-11-04 15:16
@tabarr Can you change the setting and test it with your slave device?

**Comment by rainierwolfcastle** [comment] 2015-11-04 16:28
ARM Internal Ref: IOTSFW-1170

**Comment by 0xc0170** [comment] 2015-11-11 09:33
This should be reported for K64F - in the ksdk module. I'll close this here , please report this to ksdk hal module.

There's no method to set a delay between bytes at the moment, the default is around what you experienced.

In the spi_frequency, I added one line to reflect 1/2 cycle, should do a trick for you.

```
void spi_frequency(spi_t *obj, int hz) {
    uint32_t busClock;
    CLOCK_SYS_GetFreq(kBusClock, &busClock);
    DSPI_HAL_SetBaudRate(obj->spi.address, kDspiCtar0, (uint32_t)hz, busClock);
    DSPI_HAL_CalculateDelay(obj->spi.address, kDspiCtar0, kDspiAfterTransfer, busClock, 1000000000/(2*hz));
}

```

**Closed** 2015-11-11 09:33 UTC
Labels: mirrored

**Comment by 0xc0170** [comment] 2015-11-11 13:04
I sent PR with a patch, will default to 1/2 clock cycle, you can test it here https://github.com/ARMmbed/mbed-hal-ksdk-mcu/pull/50

Same code as I posted above.
